name: daily_report
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 3 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8.0
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.0
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install muggle-ocr -i https://mirrors.aliyun.com/pypi/simple/ --user
      - name: Send daily report
        env:
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          contact_name: ${{ secrets.contact_name }}
          contact_relation: ${{ secrets.contact_relation }}$
          contact_phone: ${{ secrets.contact_phone }}$
        run: python daily_report.py --username "$username" --password "$password" --contact_name "$contact_name" --contact_relation "$contact_relation" --contact_phone "$contact_phone"